# hyparameters for Deep-Q learning
device: 'cpu'

n_actions: 3 # [straight, right, left]
target_update_step: 20
max_memory: 100000
batch_size: 1000
lr: 0.001
gamma: 0.9
lamda: 0.1
lr_update_step: 500

e_greedy:
  eps_start: 0.9
  eps_end: 0.01
  eps_decay: 100

reward:
  alpha: -1
  apple: 20
  collision: -10

DQN:
  pretrained: False #'saved_model/model_DDQN.pth'
  DDQN: True
  input_size: 11
  output_size: 3

